# Generated by Django 4.2.7 on 2025-09-27 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
                ('memory_total', models.BigIntegerField(blank=True, null=True)),
                ('memory_available', models.BigIntegerField(blank=True, null=True)),
                ('memory_percent', models.FloatField(blank=True, null=True)),
                ('memory_used', models.BigIntegerField(blank=True, null=True)),
                ('swap_total', models.BigIntegerField(blank=True, null=True)),
                ('swap_used', models.BigIntegerField(blank=True, null=True)),
                ('swap_percent', models.FloatField(blank=True, null=True)),
                ('cpu_count', models.IntegerField(blank=True, null=True)),
                ('cpu_count_logical', models.IntegerField(blank=True, null=True)),
                ('load_average', models.CharField(blank=True, max_length=100, null=True)),
                ('disk_total', models.BigIntegerField(blank=True, null=True)),
                ('disk_used', models.BigIntegerField(blank=True, null=True)),
                ('disk_free', models.BigIntegerField(blank=True, null=True)),
                ('disk_percent', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'System Statistics',
                'verbose_name_plural': 'System Statistics',
                'ordering': ['-timestamp'],
            },
        ),
    ]
